export const DogRaces = [
  {
    name: "chihuahua",
    need: 60,
    img: "/chihuahua.webp",
    activity_level: 30,
    exercise_needs: "Low to moderate",
    life_span: "between 12-18 years",
    learn_more: "https://dogtime.com/dog-breeds/chihuahua",
  },
  {
    name: "bulldog",
    need: 60,
    img: "/bulldog.jpg",
    activity_level: 15,
    exercise_needs: "Low",
    life_span: "between 8-10 years",
    learn_more: "https://dogtime.com/dog-breeds/bulldog",
  },
  {
    name: "poodle",
    need: 60,
    img: "/poodle.jpg",
    activity_level: 30,
    exercise_needs: "Moderate",
    life_span: "between 12-15 years",
    learn_more: "https://dogtime.com/dog-breeds/poodle",
  },
  {
    name: "Jack Russell",
    need: 180,
    img: "/JackRussel.webp",
    activity_level: 95,
    exercise_needs: "High",
    life_span: "between 13-16 years",
    learn_more: "https://dogtime.com/dog-breeds/jack-russell-terrier",
  },
];
